server/config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :connections
  resources :tweets, shallow: true do
    resources :comments
  end
  resources :users do
    collection do
      post :login
      get :currentUser
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/connection.rb
class Connection
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user

  before_save :set_time_stamps

  field :to_user, type: BSON::ObjectId
  field :blocked, type: Boolean
  field :blocked_at, type: DateTime

  private
  def set_time_stamps
    self.created_at = Time.now unless self.created_at
    self.updated_at = Time.now
  end
end

server/app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:show, :edit, :update, :destroy]

  # GET /connections
  # GET /connections.json
  def index
    @connections = Connection.all
  end

  # GET /connections/1
  # GET /connections/1.json
  def show
  end

  # GET /connections/new
  def new
    @connection = Connection.new
  end

  # GET /connections/1/edit
  def edit
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(connection_params)

    respond_to do |format|
      if @connection.save
        format.html { redirect_to @connection, notice: 'Connection was successfully created.' }
        format.json { render :show, status: :created, location: @connection }
      else
        format.html { render :new }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1
  # PATCH/PUT /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        format.html { redirect_to @connection, notice: 'Connection was successfully updated.' }
        format.json { render :show, status: :ok, location: @connection }
      else
        format.html { render :edit }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to connections_url, notice: 'Connection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection
      @connection = Connection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_params
      params.fetch(:connection, {})
    end
end

server/app/helpers/connections_helper.rb
module ConnectionsHelper
end

server/app/views/connections/_form.html.erb
<%= form_for(connection) do |f| %>
  <% if connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% connection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/connections/edit.html.erb
<h1>Editing Connection</h1>

<%= render 'form', connection: @connection %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

server/app/views/connections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Connections</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @connections.each do |connection| %>
      <tr>
        <td><%= link_to 'Show', connection %></td>
        <td><%= link_to 'Edit', edit_connection_path(connection) %></td>
        <td><%= link_to 'Destroy', connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Connection', new_connection_path %>

server/app/views/connections/new.html.erb
<h1>New Connection</h1>

<%= render 'form', connection: @connection %>

<%= link_to 'Back', connections_path %>

server/app/views/connections/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_connection_path(@connection) %> |
<%= link_to 'Back', connections_path %>