server/config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :connections
  resources :tweets, shallow: true do
    resources :comments
  end
  resources :users do
    collection do
      post :login
      get :currentUser
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

server/app/models/request.rb
class Request
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user

  before_save :set_time_stamps

  field :to_user, type: BSON::ObjectId
  field :rejected, type: Boolean
  field :rejected_at, type: DateTime

  private
  def set_time_stamps
    self.created_at = Time.now unless self.created_at
    self.updated_at = Time.now
  end
end

server/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :validate_token

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.fetch(:request, {})
    end
end

server/app/helpers/requests_helper.rb
module RequestsHelper
end

server/app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

server/app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

server/app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

server/app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>